import Head from 'next/head'
import Image from 'next/image'
import React, {useEffect, useState} from 'react'
import styles from '../styles/Home.module.css'
import { supabase } from '../utils/supabaseClient'
import Posts from '../components/Posts'
import useSWR from 'swr'

const fetcher = (url) => fetch(url, {method: 'GET'}).then(res => res.json());

export default function Home() {

  const [title, setTitle] = useState('')
  const [content,setContent] = useState('')

  const {data: posts ,error} = useSWR('api/posts', fetcher)
 

  const onSubmit = async (e) => {
    e.preventDefault()

    try {
      const {data, error} = await supabase
          .from('Posts')
          .insert([
            {title: title, content: content}
          ])
          
          if(data){
            console.log('success')
          }

    } catch (error) {
      console.log(error)
    }
    

    setTitle('')
    setContent('')
  }

  // const getTableData = async () =>{
    
  //   try {
  //     const {data, error} = await supabase
  //         .from('Posts')
  //         .select('*')
          
  //         if(data){
            
  //           setPosts(data)
  //         }

  //   } catch (error) {
  //     console.log(error)
  //   }
  // }

  // useEffect(()=>{

  //   getTableData()
  // }, [])

  return (
  
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='flex items-center justify-center  flex-col py-20'>
        
        
        <form onSubmit={onSubmit} className=' p-20 flex flex-col gap-8'>
          <h1 className="text-3xl font-bold ">
          Create a post!
        </h1>
          
          <input type='text' className='shadow p-2 border-b w-full outline-none' 
          placeholder='Title...' onChange={e => setTitle(e.target.value)} value={title} ></input>
          <input type='text' className='shadow p-2 border-b w-full outline-none' 
          placeholder='Content...' onChange={e => setContent(e.target.value)} value={content} ></input>
          <button type='submit' className='bg-blue-300 p-2 rounded' >Submit</button>
        </form>

        <div className='pb-20 flex flex-col items-center justify-center '>
        {posts && posts.map(elem =>{
          return(<Posts key={elem.id} title={elem.title} content={elem.content} />)
        })}
        </div>
        
      </main>
    </div>
  )
}
